apiVersion: v1
kind: Secret
metadata:
  name: lw-registry-user-pass
  annotations:
    build.knative.dev/docker-0: ${REGISTRY}
type: kubernetes.io/basic-auth
data:
  # this is the word "token" encoded with base64 ('echo -n "token" | base64')
  username: dG9rZW4=
  password: ${TOKEN_BASE64}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lw-build-bot
secrets:
- name: lw-registry-user-pass
