apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: cr-app-from-source
  namespace: default
spec:
  runLatest:
    configuration:
      build:
        serviceAccountName: cr-build-bot
        source:
          git:
            url: https://github.com/mchmarny/simple-app.git
            revision: master
        template:
          name: kaniko
          arguments:
          - name: IMAGE
            value: ${REGISTRY}/${NAMESPACE}/cr-app-from-source:latest
      revisionTemplate:
        spec:
          container:
            image: ${REGISTRY}/${NAMESPACE}/cr-app-from-source:latest 
            imagePullPolicy: Always
            env:
            - name: SIMPLE_MSG
              value: "Hello from the Docker image published in IBM Cloud Container Registry"
